refatorando codigo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,7 +46,10 @@ jobs:
       - name: Check Gitflow master
         run: if [[ ${{ github.event.pull_request.base.ref }} == "master" ]]; 
              then if [[ ${{ startsWith(github.event.pull_request.head.ref, 'release')}} == "false" ]]; 
-             then echo "'hotfix' prefix required for merge in master"; exit 1; fi; fi 
+             then echo "'hotfix' prefix required for merge in master"; 
+             exit 1; 
+             fi; 
+             fi 
 
       - name: Check Base release
         if: ${{ github.event.pull_request.base.ref == 'release' }}
