new re

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,51 +9,74 @@ on:
   pull_request:
   
 jobs:
-  lint:
+          
+  golangci:
     name: Lint
     runs-on: ubuntu-latest
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v1
+        uses: actions/setup-go@v3
         with:
           go-version: 1.18
-
       - name: Check out code
-        uses: actions/checkout@v1
-
+        uses: actions/checkout@v3
       - name: Lint Go Code
-        run: |
-          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
-          go get -u golang.org/x/lint/golint 
-          
-          
+        uses: golangci/golangci-lint-action@v3
+
   test:
     name: Test
     runs-on: ubuntu-latest
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v1
+        uses: actions/setup-go@v3
         with:
           go-version: 1.18
 
       - name: Check out code
-        uses: actions/checkout@v1
+        uses: actions/checkout@v3
 
-      - name: Run Unit tests.
-        run: make test-coverage
+      - name: Run unit Tests.
+        run: go test -cover -race -vet=off ./...
       
+  GitFlow:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Check Gitflow hotfix
+        run: if [[ ${{ github.event.pull_request.base.ref }} == "master" ]];
+             then if [[ ${{ startsWith(github.event.pull_request.head.ref, 'hotfix')}} == "false" ]]; 
+             then echo "'hotfix' prefix required for merge in master"; 
+             exit 1; 
+             fi; 
+             fi
+      - name: Check Gitflow release
+        run: if [[ ${{ github.event.pull_request.base.ref }} == "master" ]];
+             then if [[ ${{ startsWith(github.event.pull_request.head.ref, 'release')}} == "false" ]]; 
+             then echo "'release' prefix required for merge in master"; 
+             exit 1; 
+             fi; 
+             fi       
+      - name: Check Gitflow feature
+        run: if [[ ${{ github.event.pull_request.base.ref }} == "develop" ]];
+             then if [[ ${{ startsWith(github.event.pull_request.head.ref, 'feature')}} == "false" ]]; 
+             then echo "'feature' prefix required for merge in develop"; 
+             exit 1; 
+             fi; 
+             fi 
+
   build:
     name: Build
     runs-on: ubuntu-latest 
-    needs: [lint, test]
+    needs: [golangci, test, GitFlow]
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v1
+        uses: actions/setup-go@v3
         with:
           go-version: 1.18
 
       - name: Check out code
-        uses: actions/checkout@v1
+        uses: actions/checkout@v3
 
       - name: Build
         run: go build -v ./...
